### ISSUE TITLE
Assemble ARM packages

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-indexer#111]
## Description

We haven't been able to generate ARM packages as we need custom runners to build them.

To be extended...

## Tasks

- [x] Create ARM GH Workflow runner.
- [x] Assemble ARM packages.

**Comment by havidarou** [comment]
Won't do. OpenSearch does not offer packages in this architecture.

**Comment by s482dcaw** [comment]
The last OpenSearch version is 2.12.0 and there are arm64 packages, for Debian (opensearch-2.12.0-linux-arm64.deb), RedHat, tarballs... Is this ticket about ARM (32bit), assuming that arm64 is going to be supported?

**Comment by AlexRuiz7** [comment]
We won't support ARM architectures for the time being.
