### ISSUE TITLE
Amazon Security Lake integration - DTD - Python script

### ISSUE THREAD

**Issue by f-galland** [wazuh/wazuh-indexer#144]
## Description

A middle point between creating a Logstash output plugin or codec to send binary data to S3 and using a Lambda function with an auxiliary S3 bucket is to continue the Logstash pipeline with a custom script that transforms and uploads the data.

The benefits of this approach are:

- The data transformation and upload process is independent of the Logstash's ingest pipeline.
- The script can be self-hosted, reducing costs.
- The script can be used for future integrations starring `integratord`.
- Agile development, as Python is a language we are confident with, unlike Ruby.
- We do not need to learn and comply with Logstash's plugins development requirements and lifecycle.

## Functional requirements

* Read data from the Logstash's pipeline.
* Transform our data to OCSF compatible schema.
* Encode our data as Apache Parquet.
* Upload the data to an S3 bucket.

## Implementation restrictions

* The Logstash pipeline will invoke our script using the [pipe output plugin](https://www.elastic.co/guide/en/logstash/8.12/plugins-outputs-pipe.html), so the script must be able to read the data from standard input.
* To upload the data, use [AWS SDK for Python (Boto3)](https://boto3.amazonaws.com/v1/documentation/api/latest/index.html).
* Ensure data encryption is enabled and pay special attention to safe handling of AWS credentials.

## Additional information

As a guideline, check how other companies do it. For example, [CrowdStrike](https://docs.aws.amazon.com/security-lake/latest/userguide/integrations-third-party.html#integration-crowdstrike).

**Comment by kclinden** [comment]
What are you thinking for mapping Wazuh events to OCSF event classes? Will you likely do it as a single class of "Security Finding(2001)" or will you try to break it out to various classes?

**Comment by f-galland** [comment]
> What are you thinking for mapping Wazuh events to OCSF event classes? Will you likely do it as a single class of "Security Finding(2001)" or will you try to break it out to various classes?

For the time being, we are researching various approaches to the pipeline mechanism itself as the OCSF mapping is being developed in parallel to our effort here.

**Comment by AlexRuiz7** [comment]
> What are you thinking for mapping Wazuh events to OCSF event classes? Will you likely do it as a single class of "Security Finding(2001)" or will you try to break it out to various classes?

We are investigating that and should have a reply shortly. In the meantime, we'll use the "Security Finding(2001)" class, fill the required values, and include the rest of the data in the "unmapped" field, so we can test whether the integration works, even if it's not mapped properly yet.

We'd like to use various classes, but we'll see.

**Comment by f-galland** [comment]
Now that we have a [docker testing environment](https://github.com/wazuh/wazuh-indexer/issues/160), we are moving back to this one.
In my tests I'm also including a `s3.ninja` local bucket for ease of debugging.

In order to authenticate and write to a local S3 bucket using pyarrow, we need to explicitly instantiate a `fs.S3FileSystem` object in order to set the `endpoint_override` parameter to the local bucket's IP address and listening port.

I've opted for using `boto3` to handle reading the `.aws/credentials` file so as to be able to read a single profile's credentials as well.

As of right now, the logic for this lives within a function, but this should ideally be moved out to a class.

**Comment by f-galland** [comment]
The current date (used for the files' timestamps) was being evaluated at the begging of the main block and not within the loop.
Moving it to the appropriate spot now generates files properly.

![Image](https://github.com/wazuh/wazuh-indexer/assets/99492720/a3909651-112d-4ab5-954b-69b86c98ea49)

**Comment by AlexRuiz7** [comment]
Latest update on https://github.com/wazuh/wazuh-indexer/pull/186#issuecomment-2006985534
