### ISSUE TITLE
Wazuh Indexer doesn't start 

### ISSUE THREAD

**Issue by pulpon6** [wazuh/wazuh-indexer#202]
## Description

- Version: 4.7.0-1
- Installation method: Step by Step
- Operating System: Almalinux 8.7

On Monday I tried to upgrade my server package and wazuh to the new version 4.5.0 to 4.7.0-1 and after reboot the server wazuh-indexer doesn't start anymore

**Comment by AlexRuiz7** [comment]
Closed due to inactivity.

**Comment by hanangp** [comment]
Maybe because chown folder backup is root. Change ownership to wazuh-indexer and start again wazuh index

<img width="577" height="264" alt="Image" src="https://github.com/user-attachments/assets/840ba181-003f-4a80-a9e5-7d83bcb97746" />
