### ISSUE TITLE
`systemctl start wazuh-indexer` not working

### ISSUE THREAD

**Issue by orhancevik64** [wazuh/wazuh-indexer#203]
I ve installed Wazuh on my virtuell Debian environment but when i give the last command systemctl start wazuh-indexer, i take the error in picture which i added.

Does anyone has any idea?

thanks
![wazuh_error](https://github.com/wazuh/wazuh/assets/139228105/471ba137-1326-4c95-b7a3-fc9b2e7ff7da)

**Comment by amarkhade96** [comment]
> Have you checked the logs as suggested?

Yes but was not able to identify the error

**Comment by amarkhade96** [comment]
[
<img width="660" alt="wazuh_Error" src="https://github.com/wazuh/wazuh-indexer/assets/49128616/2cfba4c7-f411-4bc6-b043-f0933edfecae">
]

**Comment by amarkhade96** [comment]
@AlexRuiz7  Can you help

**Comment by AlexRuiz7** [comment]
Check the service logs with on `journald`

```
journalctl --no-pager --since yesterday -xeu wazuh-indexer
```

Also, check the logs at `/var/log/wazuh-indexer/wazuh-cluster.log`

```
grep -iE "error" /var/log/wazuh-indexer/wazuh-cluster.log
```

**Comment by AlexRuiz7** [comment]
Closed due to inactivity.
