### ISSUE TITLE
Wazuh indexer build package workflow is broken

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-indexer#206]
## Description

Testing the workflows merged in the numbered branch, an error has appeared just running the workflow, we must fix this

https://github.com/wazuh/wazuh-indexer/actions/runs/8710043389

![image](https://github.com/wazuh/wazuh-indexer/assets/14913942/9ee51178-6f11-4265-be8c-31c255c25839)

### Inputs

![image](https://github.com/wazuh/internal-devel-requests/assets/14913942/283211cd-2c73-4ef0-8a17-b0e72eb99af6)

Using the GitHub CLI, the workflow fails with the same error

```
gh workflow run build_single.yml --repo=wazuh/wazuh-indexer --ref 4.9.0 -f system=deb -f architecture=amd64 -f revision=999 -f is_stage=true -f checksum=true
```

![image](https://github.com/wazuh/wazuh-indexer/assets/14913942/e3d1bbd1-e1f6-4f8e-9f2b-b98e259114de)

**Comment by AlexRuiz7** [comment]
Looks like the inputs for `on.workflow_call` can only be `string`, `boolean` or `number`.

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_callinputsinput_idtype

This doesn't meet the requirements agreed for this development, which was to use `choice`.

We can fix that, using `string` instead.

@rauldpm
