### ISSUE TITLE
Define fields for stateful modules data

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-indexer#282]
**Parent issue:**:

- https://github.com/wazuh/wazuh-indexer/issues/270

## Description

As part of the ongoing enhancements for Wazuh Indexer, we need to define and document the fields for the modules that produce stateful data. The specific modules in scope are:

1. **File Integrity Monitoring (FIM)**
2. **Security Configuration Assessment (SCA)**
3. **System Inventory (AKA Syscollector)**

These fields will be essential for ensuring consistent and comprehensive data handling across the platform.

## Requirements

- Create a table for each module listed above.
- Each table should include the following columns:
  - **Field name**: The name of the field.
  - **ECS field name**: Mapping to ECS.
  - **Data type**: The type of data stored.
  - **Description**: A brief description of what the field represents.
- Ensure the fields cover all necessary aspects of the data produced by these modules.

**Comment by vikman90** [comment]
## Tables

Based  on  file: [**schema_agents.sql**](https://github.com/wazuh/wazuh/blob/4.9.0/src/wazuh_db/schema_agents.sql)

### File Integrity Monitoring

|   | Field name    | ECS name | Data type  | Description            |
|---|---------------|----------|------------|------------------------|
|   | full_path     |          | TEXT       | Full path of the item  |
|   | file          |          | KEYWORD    | File name              |
|   | type          |          | KEYWORD    |                        |
| ❌ | date          |          |            |                        |
| ❌ | changes       |          |            |                        |
|   | arch          |          | KEYWORD    |                        |
|   | value_name    |          | TEXT       |                        |
|   | value_type    |          | KEYWORD    |                        |
|   | size          |          | LONG       |                        |
|   | perm          |          | TEXT       |                        |
|   | uid           |          | LONG       |                        |
|   | gid           |          | LONG       |                        |
|   | md5           |          | KEYWORD  ❓ |                        |
|   | sha1          |          | KEYWORD ❓  |                        |
|   | uname         |          | TEXT       |                        |
|   | gname         |          | TEXT       |                        |
|   | mtime         |          | LONG ❓     | Last modification time |
|   | inode         |          | LONG       |                        |
|   | sha256        |          | KEYWORD ❓  |                        |
|   | attributes    |          | TEXT       |                        |
|   | symbolic_path |          | TEXT       |                        |
| ❌ | checksum      |          |            |                        |

**Comment by cborla** [comment]
## Tables

Based on file: [schema_agents.sql](https://github.com/wazuh/wazuh/blob/4.9.0/src/wazuh_db/schema_agents.sql)

### Security Configuration Assessment (SCA)

| Field name    | ECS field name      | Data type | Description                                              |
|---------------|---------------------|-----------|----------------------------------------------------------|
| scan_id       | event.id            | INTEGER   | Reference to the scan information                        |
| id            | event.sequence      | INTEGER   | Primary key for the check                                |
| policy_id     | policy.id           | KEYWORD   | Reference to the policy                                  |
| title         | rule.name           | TEXT      | Title of the check                                       |
| description   | rule.description    | TEXT      | Description of the check                                 |
| rationale     |                     | TEXT      | Rationale behind the check                               |
| remediation   |                     | TEXT      | Steps for remediation                                    |
| file          | file.path           | KEYWORD   | File related to the check                                |
| process       | process.name        | KEYWORD   | Process related to the check                             |
| directory     | file.directory      | KEYWORD   | Directory related to the check                           |
| registry      | registry.path       | KEYWORD   | Registry related to the check                            |
| command       | process.command_line| TEXT      | Command related to the check                             |
| references    | rule.references     | TEXT      | References for the check                                 |
| result        | event.outcome       | KEYWORD   | Result of the check                                      |
| reason        |                     | TEXT      | Reason for the result                                    |
| condition     |                     | TEXT      | Condition that triggers the check                        |

**Comment by cborla** [comment]
## Tables

Based on file: [schema_agents.sql](https://github.com/wazuh/wazuh/blob/4.9.0/src/wazuh_db/schema_agents.sql)

### System Inventory (Syscollector)

|| Field name         | ECS field name   | Data type | Description                                                  |
|---|--------------------|------------------|-----------|--------------------------------------------------------------|
| | scan_id            | event.id         | INTEGER   | Reference to the scan information                            |
| | scan_time          | `@timestamp`       | DATE      | Timestamp of the scan                                        |
| | hostname           | host.hostname    | KEYWORD   | Hostname of the system                                       |
| | architecture       | host.architecture| KEYWORD   | System architecture                                          |
| | os_name            | os.name          | KEYWORD   | Name of the operating system                                 |
| | os_version         | os.version       | KEYWORD   | Version of the operating system                              |
| | os_codename        | os.codename      | KEYWORD   | Codename of the operating system                             |
| | os_major           | os.version_major | KEYWORD   | Major version number of the operating system                 |
| | os_minor           | os.version_minor | KEYWORD   | Minor version number of the operating system                 |
| | os_patch           | os.version_patch | KEYWORD   | Patch version number of the operating system                 |
| | os_build           | os.build         | KEYWORD   | Build version of the operating system                        |
| | os_platform        | os.platform      | KEYWORD   | Platform of the operating system                             |
| | sysname            |                  | KEYWORD   | System name                                                  |
| | release            |                  | KEYWORD   | System release                                               |
| | version            |                  | KEYWORD   | System version                                               |
| | os_release         | os.version       | KEYWORD   | Operating system release version                             |
| | checksum           | file.hash.md5    | KEYWORD   | Checksum of the scan                                         |
| | os_display_version | os.version       | KEYWORD   | Display version of the operating system                      |
| | reference          |                  | KEYWORD   | Reference information                                        |

**Comment by vikman90** [comment]
We reopen this issue.

For the specific case of the operating system inventory, we will need:
1. Create a new table with examples of each current field, for Linux, Windows and macOS.
2. Define with @dwordcito which fields are necessary for Vulnerability Detection.

**Comment by vikman90** [comment]
## OS inventory table

| Field          | Linux                                    | Windows                                  | macOS                                                                                                  |
|----------------|------------------------------------------|------------------------------------------|--------------------------------------------------------------------------------------------------------|
| `scan_id`      | 0                                        | 0                                        | 0                                                                                                      |
| `scan_time`    | 2024/06/28 12:06:56                      | 2024/06/28 12:12:44                      | 2024/06/28 12:07:39                                                                                    |
| `hostname`     | Rocket                                   | ROCKET                                   | Vikmans-MacBook-Pro.local                                                                              |
| `architecture` | x86_64                                   | x86_64                                   | arm64                                                                                                  |
| `os_name`      | Ubuntu                                   | Microsoft Windows 11 Pro                 | macOS                                                                                                  |
| `os_version`   | 24.04 LTS (Noble Numbat)                 | 10.0.22631.3737                          | 14.5                                                                                                   |
| `os_codename`  | noble                                    |                                          | Sonoma                                                                                                 |
| `os_major`     | 24                                       | 10                                       | 14                                                                                                     |
| `os_minor`     | 04                                       | 0                                        | 5                                                                                                      |
| `os_build`     |                                          |                                          | 23F79                                                                                                  |
| `os_platform`  | ubuntu                                   | 22631.3737                               | darwin                                                                                                 |
| `sysname`      | Linux                                    | windows                                  | Darwin                                                                                                 |
| `release`      | 5.15.153.1-microsoft-standard-WSL2       | 2009                                     | 23.5.0                                                                                                 |
| `version`      | #1 SMP Fri Mar 29 23:14:13 UTC 2024      | 1719576763000555500                      | Darwin Kernel Version 23.5.0: Wed May  1 20:13:18 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6030 |
| `checksum`     | 1719576416746634351                      | 23H2                                     | 1719576458594152                                                                                       |
| `reference`    | d0241780a708ba1e2a1a54762c15b2e3c75aabc8 | c6be314466fb7ad4d7a78462fc3d05c49231fbd5 | 2419f871e6668f5f4e67c75fbb92b3ab48e830f4                                                               |
