### ISSUE TITLE
Scheduled upward merges for numbered branches in wazuh-indexer repository - Fortnight #11

### ISSUE THREAD

**Issue by fcaffieri** [wazuh/wazuh-indexer#295]
## Description

The goal is to complete the following tasks, each task must have a PR associated with this issue.

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, `merge-4.8.1-into-4.9.0`.

### 4.8.1
- [ ] Update changelog.
- [ ] Review wazuh-packages 4.8.1 Wazuh indexer changes
- [ ] Migrate changes from wazuh-packages branch `4.8.1` into branch `4.9.0`.

**Comment by AlexRuiz7** [comment]
`wazuh-indexer` repository starts from 4.9.0. No action needed.

**Comment by rauldpm** [comment]
The wazuh-indexer repository was created for 4.9.0, but we have a Wazuh indexer in the wazuh-packages repository. We need to ensure we have the wazuh-indexer repository is updated with the latest changes (if they exist).

**Comment by AlexRuiz7** [comment]
There are no changes from 4.8.1
