### ISSUE TITLE
Compatibility with OpenSearch 2.16.0

### ISSUE THREAD

**Issue by f-galland** [wazuh/wazuh-indexer#336]
## Description
We need to ensure the compatibility with the next version of OpenSearch v2.16.0
This update is still being discussed, but we need to be aware of potential issues.

For that, we need to:

- [x] Review opensearch's release notes. 
- [x] Identify improvements and potential impact.
- [x] Create new development branch.
- [x] Develop a testing environment to verify our components would work under this new build.

**Comment by f-galland** [comment]
We will reopen this when 2.16 is out. Closing it for the time being.

**Comment by AlexRuiz7** [comment]
Better to wait until 4.9.0 is out so we can easily sync the branches.

**Comment by AlexRuiz7** [comment]
### [OpenSearch 2.16.0 release notes](https://github.com/opensearch-project/OpenSearch/blob/main/release-notes/opensearch.release-notes-2.16.0.md)

- Add strict_allow_templates dynamic mapping option (https://github.com/opensearch-project/OpenSearch/pull/14555)
- ❗ Add Plugin interface for loading application based configuration templates (https://github.com/opensearch-project/OpenSearch/issues/14659)
- Add logic to create index templates (v2) using context field (https://github.com/opensearch-project/OpenSearch/pull/14811)
- ❗ Deprecate batch_size parameter on bulk API (https://github.com/opensearch-project/OpenSearch/pull/14725)
