### ISSUE TITLE
[MVP Checkpoint] Implement Wazuh Indexer packaging

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-indexer#414]
## Description

As part of the ongoing development of the new Data Persistence Model, we need to ensure that the Wazuh Indexer can be installed on the host system and run as a background service, utilizing the system's built-in tools (packaging managers, Systemd, etc.). This issue aims to implement the following key components:

1. Ensure the Wazuh Indexer can run as a background service (daemon).
2. Develop system services for the Indexer to run on Linux.
3. Implement standard package management (RPM, DEB) for Wazuh Indexer installation.

## Functional Requirements

- The Wazuh Indexer should run as a background process (daemon) across supported systems.
- The system must offer the capability to start, stop, and restart the Indexer manually. The default behavior (enabled/disabled) depends on the standard defined by the underlying platform.
- The Wazuh Indexer should be installable via appropriate package management systems:
  - **Linux**:
    - RPM for RHEL-based distributions.
    - DEB for Debian-based distributions.
 - The Wazuh Indexer package contains ships the new plugins:
   - Setup plugin. https://github.com/wazuh/wazuh-indexer-plugins/issues/13
   - Command Manager plugin. https://github.com/wazuh/wazuh-indexer/issues/407
   - Reporting plugin. https://github.com/wazuh/wazuh-indexer/issues/423
 - Ensure all the index templates match the data model.
 
## Non-Functional Requirements

- The installation packages should follow the conventions and standards of the target operating systems.
- The installation process should be as seamless as possible, reducing manual configuration steps.
- Clear logging of Wazuh Indexer activities must be available to facilitate troubleshooting.

## Implementation Restrictions

- The service for **Linux** must use **systemd** as the service manager, since it is widely supported across the listed distributions.
- Packaging must integrate with native package managers (_e.g._, `rpm`, `apt`, `install`) and conform to the relevant package guidelines for each platform.
- For Linux distributions without systemd support (_e.g._, CentOS 6, RHEL 6), alternative service management methods must be considered (e.g., `init`).
- The Wazuh Indexer packages are built using the GH Workflows created for this purpose.

## Plan

1. Develop and test the Indexer's ability to start and run in the background independently on each platform.
2. Develop a systemd service for the Indexer on Linux platforms.
3. Create RPM and DEB packages for Linux distributions.
4. Set up testing pipelines to ensure proper installation and service functionality.
5. **Documentation:**
   - Create installation and service management documentation for system administrators.
   - Provide instructions for package installation, service control, and troubleshooting.

**Comment by miguellords** [comment]
try this
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic
I put the necessary dlls in the archive

**Comment by AlexRuiz7** [comment]
Every requirement described in this issue are fulfilled. The documentation will be worked on a future objective.
