### ISSUE TITLE
Unable to locate package libgconf-2-4 when provisioning the package building environment

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-indexer#456]
**Describe the bug**

The package generation is failing due to the following dependency error

```
Unable to locate package libgconf-2-4
```

**To Reproduce**
1. Run the GHA action https://github.com/wazuh/wazuh-indexer/actions/runs/11332275619/job/31514052126 for the v4.10.0-alpha2 tag

**Expected behavior**
The package should be created without error

**Plugins**
Default

**Screenshots**
Not needed, check links

**Host/Environment (please complete the following information):**

**Additional context**

GHA action: https://github.com/wazuh/wazuh-indexer/actions/runs/11332275619/job/31514052126

```
 Reading state information...
Package libasound2 is a virtual package provided by:
  liboss4-salsa-asound2 4.2-build2020-1ubuntu3
  libasound2t64 1.2.11-1build2 (= 1.2.11-1build2)

E: Package 'libasound2' has no installation candidate
E: Unable to locate package libgconf-2-4
Error: Process completed with exit code 100.
```

**Comment by f-galland** [comment]
The `docker` based build environments do seem to work on the tag, but they are using ubuntu `jammy`.

The github actions scripts are using `ubuntu:latest`, so dependencies might have changed with the recent release of `24.10` Oracular Oriole.

I'm testing this under a virtual machine to confirm this is actually the case.

**Comment by f-galland** [comment]
It looks like the `latest` tag from ubuntu points to `noble` (24.04) still.

**Comment by f-galland** [comment]
A docker environment pulling `ubuntu:latest` confirms this:

```shellsession
Package libasound2 is a virtual package provided by:
  liboss4-salsa-asound2 4.2-build2020-1ubuntu3
  libasound2t64 1.2.11-1build2 (= 1.2.11-1build2)
You should explicitly select one to install.

E: Package 'libasound2' has no installation candidate
E: Unable to locate package libgconf-2-4
root@ubuntu2404:~# cat /etc/os-release 
PRETTY_NAME="Ubuntu 24.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.1 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
```

**Comment by f-galland** [comment]
It looks like removing `libasound2`, `libgconf-2.4` and `freeglut3` from the dependency list fixes the issue with no noticeable downsides.
* https://github.com/wazuh/wazuh-indexer/actions/runs/11333817377
