### ISSUE TITLE
Warning and error messages found in 4.10.0 Alpha-2 OVA

### ISSUE THREAD

**Issue by hossam1522** [wazuh/wazuh-indexer#480]
| Version | Revision | Production/Development | Component | Install type |
|:--:|:--:|:--:|:--:|:--:|
|  4.10.0  |  Alpha 2  |  Development  |  wazuh-indexer  | Download | 

## Description

While analyzing logs in https://github.com/wazuh/wazuh/issues/26438#issuecomment-2427071537, some new error and warning logs were found in wazuh-indexer. Further investigation is required.

### Environment

The environment is the following OVA https://packages-dev.wazuh.com/pre-release/vm/wazuh-4.10.0.ova deployed locally in VirtualBox.

### Steps to reproduce

1. Download the OVA https://packages-dev.wazuh.com/pre-release/vm/wazuh-4.10.0.ova

2. Deploy it in VirtualBox

3. Use the following command: `grep -R -i -E "error|critical|fatal|warning" /var/log/wazuh-indexer/`

### Current result

The error and warning logs obtained are the following:

```console
/var/log/wazuh-indexer/wazuh-cluster.log:[2024-10-21T17:55:18,600][WARN ][stderr                   ] [node-1] WARNING: A restricted method in java.lang.foreign.Linker has been called
/var/log/wazuh-indexer/wazuh-cluster.log:[2024-10-21T17:55:18,600][WARN ][stderr                   ] [node-1] WARNING: java.lang.foreign.Linker::downcallHandle has been called by the unnamed module
/var/log/wazuh-indexer/wazuh-cluster.log:[2024-10-21T17:55:18,600][WARN ][stderr                   ] [node-1] WARNING: Use --enable-native-access=ALL-UNNAMED to avoid a warning for this module
/var/log/wazuh-indexer/wazuh-cluster.log:[2024-10-21T17:55:26,150][ERROR][o.o.s.l.BuiltinLogTypeLoader] [node-1] Failed loading builtin log types from disk!
/var/log/wazuh-indexer/wazuh-cluster.log:       at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138) [opensearch-cli-2.16.0.jar:2.16.0]
```

### Expected result

These warning and error logs should not appear.

### Attachments

- Link to download the OVA: https://packages-dev.wazuh.com/pre-release/vm/wazuh-4.10.0.ova

- Logs: [wazuh-cluster.log](https://github.com/user-attachments/files/17464407/wazuh-cluster.log)

**Comment by AlexRuiz7** [comment]
Caused by OpenSearch's security-analytics plugin:

- https://github.com/opensearch-project/security-analytics/issues/1312

**Comment by AlexRuiz7** [comment]
Close in favor of #488
