### ISSUE TITLE
Failed loading builtin log types from disk

### ISSUE THREAD

**Issue by CarlosALgit** [wazuh/wazuh-indexer#488]
# Description
While performing the [v4.10.0-alpha2 Installation Assistant test](https://github.com/wazuh/wazuh/issues/26446) I found that error in the Wazuh Indexer logs:

```
[2024-10-22T13:03:15,665][ERROR][o.o.s.l.BuiltinLogTypeLoader] [node-1] Failed loading builtin log types from disk!
```

It has been seen in `Amazon Linux 2023`, `Ubuntu 22.04` and `RHEL 9` OSs.
You can see the full Wazuh Indexer log [here](https://github.com/wazuh/wazuh/issues/26446#issuecomment-2429635521).

**To Reproduce**
1. Perform an AIO installation with the Installation Assistant with the `4.10.0` version.
2. Check the `/var/log/wazuh-indexer/wazuh-cluster.log` log file.

**Additional context**
As you can see in the referred test, the deployment finished successfully, so it is not a bug that breaks the Wazuh installation process for now.

**Comment by AlexRuiz7** [comment]
Caused by OpenSearch's security-analytics plugin:

- https://github.com/opensearch-project/security-analytics/issues/1312

There is no fix available yet.
