### ISSUE TITLE
Add Imposter to our development tools

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-indexer#500]
## Description

The Command Manager plugin is interacting with an HTTP RESTful API in the Wazuh Server. We need to mock this service to develop and test our code, avoiding setting up a complete Wazuh Server.

As for now, the Command Manager interacts with the Management API (`M_API`) in two ways:

- `POST /security/user/authenticate`, to log in to the API and obtain a JWT token.
- `POST /orders/`, to send the pending orders.

We need to mock these 2 endpoints to test our code under different behaviors, success and failure, to properly handle them.

The @wazuh/devel-dashboard team has been using [Imposter][imposter-dashboard] as a mock server for quite some time now. We'll also use this tool as we are already familiar with it, and has proven to fit our needs.

[Imposter][imposter] allows different deployment methods that can be useful for us:

- imposter-cli: easy and straightforward to set up and use.
- Docker: most portable solution.
- JAR: the way to go to include it in our development and testing environment. Requires most effort.

Imposter can be configured to load an OpenAPI spec file and to respond to whatever we need on each endpoint call. The most recent spec for the Management API is [here](https://raw.githubusercontent.com/wazuh/wazuh/42c8b4c134b4971d39c75cfff117193a5d59244f/api/api/spec/spec.yaml).

https://github.com/wazuh/wazuh/blob/enhancement/25599-server-orders-distribution/api/api/spec/spec.yaml

## Functional requirements

- Imposter responds to `POST /security/user/authenticate` providing a valid JWT token.
- Imposter responds to `POST /orders/`, with a valid JSON reply, as specified in the spec.
- Imposter loads the specified OpenAPI spec file. We may need to change often, for example, to test changes that are under development on a particular Git branch.

## Plan

- [x] Include Imposter to our tooling.
- [x] Create an appropriate user manual for this tool.
- [x] Include Imposter to the Command Manager test dependencies for automatic testing.
- [ ] Create tests that use the mock server.

[imposter]: https://docs.imposter.sh/
[imposter-dashboard]: https://github.com/wazuh/wazuh-dashboard-plugins/tree/master/docker/imposter

**Comment by AlexRuiz7** [comment]
To reuse the JS script to generate a valid token from the Wazuh Dashboard tooling, we need to add this environment variable.

```console
export IMPOSTER_JS_PLUGIN=js-graal-compat 
```

https://github.com/outofcoffee/imposter/issues/581

**Comment by mcasas993** [comment]
I had problems with import the necessaries classes to include Imposter in the unit tests. It's not urgent to include imposter in the unit tests, so I opened an [issue](https://github.com/outofcoffee/imposter/issues/660) in the Imposter repository.
