### ISSUE TITLE
Events generator for 5.x indices

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-indexer#518]
## Description

Wazuh 5.x includes a new set of indices, for which we need appropriate tooling for internal testing environments. Some of the indices already have its event generator. The goal of this issue is to add similar events' generator for the indices that are missing them.

## Functional requirements

- There are events generators for every index (but alerts) included in 5.x (see #462).

## Implementation restrictions

- Use the existing events generator as templates to build the missing ones.
- Use Python 3 as programming language.
- Must comply with the how-to defined in https://github.com/wazuh/wazuh-indexer/tree/master/ecs

## Plan

- [x] Check which indices need an events' generator.
- [x] Include the events' generator for the `fim` index.
- [x] Include the events' generator for the `inventory-packages` index.
- [x] Include the events' generator for the `inventory-processes` index.
- [x] Include the events' generator for the `inventory-system` index.
- [x] Include the events' generator for the `inventory-hardware` index.
- [x] Include the events' generator for the `inventory-hotfixes` index.
- [x] Include the events' generator for the `inventory-networks` index.
- [x] Include the events' generator for the `inventory-port` index.

**Comment by QU3B1M** [comment]
Tooling event_generator implemented on all the missing indices, also some improvements were added to the existing tools, such as replacing general warning suppression to just the required ones (`urllib3` related), and default values on the inputs.

The command event generator was outdated, it wasn't working correctly, so it was updated to work with the actual status of the plugin

**Comment by AlexRuiz7** [comment]
@f-galland is adding new indices in #270 

Let's generate events' generators for these indices too.

**Comment by QU3B1M** [comment]
All the _event_generators_ were updated with the latest changes on the indices applied on master
