### ISSUE TITLE
Unify `wazuh-indexer` build process

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-indexer#522]
## Description

Currently, the process to generate wazuh-indexer packages is split in two phases, build and assembly. While the build process consists of compiling the Java source code of indexer and bundling it alone into a package (deb, rpm or tar), the assembly process takes this bundle as input, extracts it, includes plugins and configurations and bundles it back as the final package ready to deliver.

The goal of this issue is to unify the process into a single step by using a Dockerfile that wraps both processes, making it transparent to the final user.

Although this is of great interest for bundling wazuh-indexer packages locally, I think our current process in GitHub Actions already fits this use case as it's all done in one run, so we can leave that untouched.

To summarize, the process to build packages locally must be improved to reduce user interaction as much as possible.

## Functional requirements

- The build process clones and builds our plugins before building indexer.
- The build process clones and build wazuh-indexer.
- Packages are assembled with plugins, indexer and configuration files.

## Implementation restrictions

- Use Docker to wrap all the process to build packages.
- Apart from Docker, no additional dependencies are required.
- Packages can be built using a one-line command: `docker run <image> <args>`

## Plan

- [x] Generate Docker images to build and assembly wazuh-indexer packages (existing ones can be reused).
- [x] Build Wazuh Indexer plugins automatically.
- [x] Generate a GitHub workflow to build and push the Docker images.
- [x] Update documentation
  - [x] Wazuh documentation https://github.com/wazuh/wazuh-documentation/pull/7988#issuecomment-2501810934
  - [x] Indexer documentation
  - [x] Drive documentation

Take https://github.com/wazuh/wazuh/actions as reference.

**Comment by QU3B1M** [comment]
Completed an initial working version of the build process Dockerfile. The build process requires two different steps, the image building, and the container execution. 
There are two reasons for this approach, one is to make the image more lightweight by separating the system setup and provision from the build process execution, and the other is to be able to use `volume` that can be externally defined at the run stage, in which the resulting package will be stored.

Example usage:
1. Build the Docker image
    ```bash
    docker build -t builder .
    ```
    > If the command is being executed from another directory, such as the repository root, it should be ran this: ` docker build -t builder -f docker/builder/image/Dockerfile  docker/builder/image/`
2. Run the container
    ```bash
    docker run -v ./artifacts/dist:/artifacts/dist -e INDEXER_BRANCH=master -e INDEXER_PLUGINS_BRANCH=master -e INDEXER_REPORTING_BRANCH=master -e REVISION=0 builder
    ```
    > The variables `INDEXER_BRANCH`, `INDEXER_PLUGINS_BRANCH`, `INDEXER_REPORTING_BRANCH`, `REVISION` are optional with a default value
