### ISSUE TITLE
[WARN] - Falling back to single shard assignment since batch mode disable or multiple custom allocators set

### ISSUE THREAD

**Issue by CarlosALgit** [wazuh/wazuh-indexer#551]
**Describe the bug**
During the Installation Assistant tests for 4.10.0 [alpha2](https://github.com/wazuh/wazuh/issues/26446#issuecomment-2429635521) and [alpha3](https://github.com/wazuh/wazuh/issues/26805#issuecomment-2470430112) I have found the following warning:

```
[2024-10-22T13:02:17,027][WARN ][o.o.c.r.a.AllocationService] [node-1] Falling back to single shard assignment since batch mode disable or multiple custom allocators set
```

As asked to the Indexer team, it seems that this is an experimental setting. A related issue from OpenSearch can be found here: https://github.com/opensearch-project/OpenSearch/issues/14744

**To Reproduce**
1. Install a Wazuh AIO
2. Check the `/var/log/wazuh-indexer/wazuh-cluster.log`

**Expected behavior**
The log should be missing

**Host/Environment (please complete the following information):**
 - OS: Amazon Linux 2023, Ubuntu 22, RHEL 9

**Comment by f-galland** [comment]
@CarlosALgit , as it is stated in the referenced opensearch link, this warning relates to a new setting by opensearch that is meant for handling large number of unassigned shards.
Batch allocation mode is disabled by default as it is still being evaluated for regressions, hence we get this warning.

In short, if you see the warning, it means that things are working as they were before `2.14`.

**Comment by AlexRuiz7** [comment]
As stated in this [comment](https://github.com/opensearch-project/OpenSearch/issues/14744#issuecomment-2316639379), this setting will be enabled by default in the future, getting rid of the warning message.

This warning does not represent any failure or risk on the Indexer side. No remediation can be applied on our side.
