### ISSUE TITLE
[BUG] `process.command_line` field mapping is not properly picked up by the dashboard

### ISSUE THREAD

**Issue by f-galland** [wazuh/wazuh-indexer#585]
## Description

The [`process.command_line` field](https://www.elastic.co/guide/en/ecs/current/ecs-process.html#field-process-command-line) is of `wildcard` type with multi-fields.
This seems to throw the dashboard off, showing `unknown` as the type:

![Image](https://github.com/user-attachments/assets/8c66d4b8-b00a-49cc-ac18-4007492a4f7a)

We need to investigate and fix the issue.

**Comment by AlexRuiz7** [comment]
ECS `process.command_line` is defined as a [multi-field](https://www.elastic.co/guide/en/ecs/current/ecs-process.html#field-process-command-line). We are probably missing the removal of the multi-fields for this field in `ecs/generate.sh`.

**Comment by f-galland** [comment]
Removing the `fields` object from the template doesn't fix the issue. Changing the type to `match_only_text` doesn't seem to work either:

```shellsession
curl -sku admin:admin -XGET https://192.168.58.254:9200/_template/states-inventory-processes | jq '."states-inventory-processes".mappings.properties.process.properties.command_line'
{
  "type": "match_only_text"
}
```

![Image](https://github.com/user-attachments/assets/838bde80-6647-4b41-ba5b-01e57b3d677c)

**Comment by f-galland** [comment]
It seems this is not the only field we see this problem with:
![Image](https://github.com/user-attachments/assets/84044dda-ce17-4627-abc5-32c5454caf66)

```shellsession
$ curl -sku admin:admin -XGET https://192.168.58.254:9200/_template/states-inventory-processes | jq '."states-inventory-processes".mappings.properties.agent.properties.host.properties.os.properties.full'
{
  "ignore_above": 1024,
  "fields": {
    "text": {
      "type": "match_only_text"
    }
  },
  "type": "keyword"
}

$ curl -sku admin:admin -XGET https://192.168.58.254:9200/_template/states-inventory-processes | jq '."states-inventory-processes".mappings.properties.agent.properties.host.properties.os.properties.name'
{
  "ignore_above": 1024,
  "fields": {
    "text": {
      "type": "match_only_text"
    }
  },
  "type": "keyword"
}
```

**Comment by f-galland** [comment]
This still happens even after removing the `fields` field (and recreating indices and index patterns):
```shellsession
(env) fede@tyner:~/src/ecs (main *)
$ curl -sku admin:admin -XGET https://192.168.58.254:9200/_template/states-inventory-processes | jq '."states-inventory-processes".mappings.properties.agent.properties.host.properties.os.properties.full'
{
  "ignore_above": 1024,
  "type": "keyword"
}
(env) fede@tyner:~/src/ecs (main *)
$ curl -sku admin:admin -XGET https://192.168.58.254:9200/_template/states-inventory-processes | jq '."states-inventory-processes".mappings.properties.agent.properties.host.properties.os.properties.name'
{
  "ignore_above": 1024,
  "type": "keyword"
}
(env) fede@tyner:~/src/ecs (main *)
$ curl -sku admin:admin -XGET https://192.168.58.254:9200/_template/states-inventory-processes | jq '."states-inventory-processes".mappings.properties.process.properties.command_line'
{
  "type": "wildcard"
}
```
![Image](https://github.com/user-attachments/assets/8eab4545-e304-4a35-ab9a-4b8c91d7644a)
