### ISSUE TITLE
Replace `wildcard` and `match_only_text` types to `keyword`

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-indexer#590]
## Description

Due to a bug in OpenSearch Dashboards not rendering supported types properly in Discover and other places of the UI, we need to change the mappings for every Wazuh index replacing  `wildcard` and `match_only_text` types with `keyword`|`text`.
 
Related issues:

- #585 

## Functional requirements

- None of the stateful indices use `wildcard` or `match_only_text` field types.
- None of the stateless (alerts, commands) indices use `wildcard` or `match_only_text` field types.

## Implementation restrictions

- The changes must be performed by updating our generation script, so the replacements are automated.
- Consider using `text` instead of `keyword` for better search behavior.

## Plan

- [x] Patch the `generate.sh` script.
- [x] Regenerate the mappings.
- [x] Update the index templates for the `setup` and `command-manager` plugins.

**Comment by f-galland** [comment]
No `wildcard` or `match_only_text` fields are present in the plugins mappings anymore:

```shellsession
(env) fede@tyner:~/IdeaProjects/wazuh-indexer-plugins/plugins (enhancement/590-replace-wildcard-and-match_only_text)
$ grep -ERl 'wildcard|match_only_text' setup/src/main/resources/

(env) fede@tyner:~/IdeaProjects/wazuh-indexer-plugins/plugins (enhancement/590-replace-wildcard-and-match_only_text)
$ grep -ERl 'wildcard|match_only_text' command-manager/src/main/resources/

(env) fede@tyner:~/IdeaProjects/wazuh-indexer-plugins/plugins (enhancement/590-replace-wildcard-and-match_only_text)
```
