### ISSUE TITLE
Integrations maintenance request [Month 12]

### ISSUE THREAD

**Issue by mcasas993** [wazuh/wazuh-indexer#604]
## Description

The Wazuh Indexer team is responsible for the maintenance of the third-party integrations hosted in the wazuh/wazuh-indexer repository. We must ensure these integrations work under new releases of the third-party software (Splunk, Elastic, Logstash, …) and our own.

For that, we need to:

-   [x] Create a pull request that upgrades the components to the latest version.
-   [x] Update our testing environments to verify the integrations work under new versions.
-   [x] Test the integrations, checking that:
  - The Docker Compose project starts without errors.
  - The data arrives to the destination.
  - All the dashboards can be imported successfully.
  - All the dashboards are populated with data.
-   [x] Finally, upgrade the compatibility matrix in integrations/README.md with the new versions.

> [!NOTE]
> * For Logstash, we use the logstash-oss image.
> * For Wazuh Indexer and Wazuh Dashboard, we use the opensearch and opensearch-dashboards images. These must match the opensearch version that we support (e.g: for Wazuh 4.9.0 it is OpenSearch 2.13.0). 

## Issues

-   _List here the detected issues_

**Comment by mcasas993** [comment]
## Wazuh Indexer Splunk integration

<details><summary>Built Docker compose</summary>

```powershell
docker compose -f compose.indexer-splunk.yml up -d                   
[+] Running 12/12
 ✔ splunk Pulled                                                                                                                                                                                      47.2s 
   ✔ a09bb1026942 Pull complete                                                                                                                                                                        2.9s 
   ✔ 59de139ab4a7 Pull complete                                                                                                                                                                        2.9s 
   ✔ 240852bc4e7c Pull complete                                                                                                                                                                       11.5s 
   ✔ 570e3b526dc7 Pull complete                                                                                                                                                                       11.5s 
   ✔ 4bd60e134244 Pull complete                                                                                                                                                                       11.6s 
   ✔ d0501d93737f Pull complete                                                                                                                                                                       39.7s 
   ✔ 4f4fb700ef54 Pull complete                                                                                                                                                                       39.7s 
   ✔ e1b7b6f16b3d Pull complete                                                                                                                                                                       43.9s 
   ✔ dcabfc195708 Pull complete                                                                                                                                                                       43.9s 
   ✔ 74f154f0ed61 Pull complete                                                                                                                                                                       43.9s 
   ✔ de8d9d75b1c5 Pull complete                                                                                                                                                                       44.0s 
[+] Running 8/8
 ✔ Container splunk-integration-generate-certs-config-1  Exited                                                                                                                                        1.3s 
 ✔ Container splunk-integration-wazuh-certs-generator-1  Exited                                                                                                                                        4.0s 
 ✔ Container splunk-integration-wazuh.indexer-1          Healthy                                                                                                                                      46.5s 
 ✔ Container splunk-integration-generator-1              Exited                                                                                                                                        4.0s 
 ✔ Container splunk-integration-wazuh.dashboard-1        Started                                                                                                                                       3.7s 
 ✔ Container splunk-integration-events-generator-1       Started                                                                                                                                      46.7s 
 ✔ Container splunk-integration-splunk-1                 Healthy                                                                                                                                      55.7s 
 ✔ Container splunk-integration-logstash-1               Started                       
```
</details>

**Comment by mcasas993** [comment]
## Wazuh indexer OpenSearch integration

- OpenSearch Version!

**Comment by mcasas993** [comment]
## Wazuh Indexer Elastic Stack integration

- Elastic version
![Image](https://github.com/user-attachments/assets/7e86f5e7-e9fb-47e9-b6c3-38174f326bed)

- Wazuh-amazon-aws-v1.0
![Image](https://github.com/user-attachments/assets/2d36df5b-4a35-489e-baaa-9bb720058f25)

- Wazuh-security-events-v1.0
![Image](https://github.com/user-attachments/assets/592ee926-2b00-4394-ad5c-91995d0b62e9)

- Wazuh-vulnerabilities-v1.0
![Image](https://github.com/user-attachments/assets/3b23e0d5-c233-4951-8471-64a02352bdb3)

- Wazuh-pci-dss-v1.0
![Image](https://github.com/user-attachments/assets/d34c7f64-eb3a-49ab-a990-6f52144c9842)

- Wazuh-incident-response-v1.0
![Image](https://github.com/user-attachments/assets/9b9c30be-147b-4b93-bc10-c8c31ff4346a)

- Wazuh-docker-listener-v1.0
![Image](https://github.com/user-attachments/assets/f7bf4715-4a11-4aae-b81c-fe54fbf287f0)

- Wazuh-malware-detection-v1.0
![Image](https://github.com/user-attachments/assets/898901e7-cc3f-4e2f-995d-d3e7a3dc1f76)

**Comment by mcasas993** [comment]
Because the dashboard did not work in the Splunk integration I tried again several times.

I stopped all the docker images that were generated, deleted them and recreated them.

I did not manage to see data in any of the Splunk dashboards again.

The only error I found within the docker containers was within the splunk-integration-logstash-1 container:
`[2024-12-20T16:28:00,367][ERROR][logstash.outputs.http ][main][a926e49c792ce0b380eac5676e5aeda3b074fa7c29d7182b845bf0c89b29cc2c] Encountered non-2xx HTTP code 400 {:response_code=>400, :url=>“https://splunk:8088/services/collector/raw”, :event=>#<LogStash::Event:0x3002948c>}`

Same error repeatedly with different Events

**Comment by AlexRuiz7** [comment]
## Wazuh to Splunk Integration

- The Docker Compose project starts and runs.
- The dashboards could be imported successfully.
- Every dashboard plots data.

<details><summary>Details</summary>
<p>

![Image](https://github.com/user-attachments/assets/8db07987-366f-4612-92af-d3ab287b3d99)

![Image](https://github.com/user-attachments/assets/986ae3a4-ab75-4932-ab47-36dd548bfdaf)

![Image](https://github.com/user-attachments/assets/70319e6c-18b5-456d-b511-1256eeecda06)

![Image](https://github.com/user-attachments/assets/7e89bc9c-2468-4c23-8014-058f2d165067)

![Image](https://github.com/user-attachments/assets/89a2804c-b04c-4f6d-b504-c2d37c52a139)

![Image](https://github.com/user-attachments/assets/54a47c1a-404f-4c3f-8fda-40e67455a92b)

![Image](https://github.com/user-attachments/assets/05fe31f3-eb10-496a-8329-d7638d9252b8)



</p>
</details>
