### ISSUE TITLE
Add `wazuh-template.json` to distribution packages

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-indexer#82]
## Description

Related issues:
- #79 
- #54
- https://github.com/wazuh/internal-devel-requests/issues/600

The packages' generation must be updated to include the `wazuh` template to:

- Archives (tar): `wazuh-indexer/config/wazuh-template.json`
- Packages (deb/rpm): `/etc/wazuh-indexer/wazuh-template.json`

The template will be downloaded from [wazuh/wazuh](https://github.com/wazuh/wazuh/blob/master/extensions/elasticsearch/7.x/wazuh-template.json).

**Comment by AlexRuiz7** [comment]
### Option 1: include `wazuh-template` in minified packages (preferable)

1. Download the wazuh-template.json from the wazuh/wazuh repo from the build.sh script, before calling `gradlew`. The download path is to be defined.
2. Update `distribution/build.gradle` to include the wazuh-template in the packages, placing it on the expected path, which is `/etc/wazuh-indexer/wazuh-template.json`


### Option 2: include the `wazuh-template` in assembled packages only

1. Download the wazuh-template.json from the wazuh/wazuh repo from the assemble.sh script.
2. Having the minified packages extracted, include the `wazuh-template` to the expected path.

**Comment by AlexRuiz7** [comment]
Check review in PR https://github.com/wazuh/wazuh-indexer/pull/116#pullrequestreview-1817982504

**Comment by f-galland** [comment]
`wazuh-template.json` gets deployed to `/etc/wazuh-indexer` with the right attributes (`660`) on `rpm` based distributions:

![DeepinScreenshot_select-area_20240116083652](https://github.com/wazuh/wazuh-indexer/assets/99492720/a0b1c800-b04d-441c-99b9-6a4e2e86c7eb)

The complete folder gets deleted after `yum remove wazuh-indexer`:


![DeepinScreenshot_select-area_20240116083739](https://github.com/wazuh/wazuh-indexer/assets/99492720/b3053c54-98f0-44a7-9686-a8d9ab626e44)


In `deb` packages, on the other hand, `wazuh-template.json` gets deployed with incorrect attributes (`644`):

![DeepinScreenshot_select-area_20240116093038](https://github.com/wazuh/wazuh-indexer/assets/99492720/465a97c7-ba55-4408-9b29-00e75ed3f201)

The package does uninstall the complete `/etc/wazuh-indexer` folder properly, though:

![DeepinScreenshot_select-area_20240116093104](https://github.com/wazuh/wazuh-indexer/assets/99492720/cdafab4e-e6b9-4e70-9780-3ff775617065)


We will handle `deb` package attributes through a separate issue.

**Comment by AlexRuiz7** [comment]
Blocking this issue as we need better Docker environments to reliable test the feature.

See https://github.com/wazuh/wazuh-indexer/pull/116#pullrequestreview-1829553647
