### ISSUE TITLE
Validate and test packages

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-indexer#99]
## Description

We have developed tools to generate packages of `wazuh-indexer` from a given commit of this repository. In order to verify that these packages are worthy, we need to validate their contents and test them.

Use previous tests as a guideline.
- https://github.com/wazuh/wazuh/issues/20703

## Tasks

For assembled RPM and DEB packages generated using our tools, we need to:

- [ ] Validate their content. We expect the packages to contain the same amount of files as in previous packages of `wazuh-indexer` ([4.7.0](https://documentation.wazuh.com/current/installation-guide/packages-list.html#wazuh-indexer)).
- [ ] Test the packages' lifecycle. We expect the packages to upgrade, install and uninstall successfully. Moreover, `wazuh-indexer` must work without errors.

## Test requirements and restrictions

During the packages' validation step, download and extract the fork (4.9.0) and pre-fork (4.7.0) packages for the same distribution (deb / rpm), and compare its contents. An example of this procedure can be seen [here](https://github.com/wazuh/wazuh-indexer/issues/76#issuecomment-1858118447).

If you find differences in their contents, note them as follows:

* New files represent a _Warning_.
* Missing files represent a _Failure_.

It is not required to verify the content of the files themselves, but do check important configuration files as `/etc/wazuh-indexer/jvm.options` and `/etc/wazuh-indexer/opensearch.yml`.

For the packages' testing step, download and install the fork (4.9.0) and pre-fork packages (4.7.0) and test that:

- Following the [upgrade guide](https://documentation.wazuh.com/current/upgrade-guide/upgrading-central-components.html#upgrading-the-wazuh-indexer), `wazuh-indexer` upgrades from 4.7.0 to 4.9.0 successfully, meaning there are no errors in the logs, the service is active, and the cluster is in green state (see the notes below for more information).
- Following the [uninstallation guide](https://documentation.wazuh.com/current/user-manual/uninstall/index.html#uninstall-the-wazuh-indexer), `wazuh-indexer` and all its contents are removed from the system.
- Following the [installation guide](https://documentation.wazuh.com/current/installation-guide/wazuh-indexer/step-by-step.html), `wazuh-indexer` installs, meaning there are no errors in the logs, the service is active, and the cluster is in green state (see the notes below for more information).
- For the installation, do also check [file permissions](https://github.com/wazuh/wazuh/issues/20703#:~:text=Key%20ID%2096b3ee5f29111145-,Wazuh%20indexer%20(%20installed%20files%2C%20location%20and%20permission),-%F0%9F%9F%A2).

## Legend

|     |     |
| --- | --- |
| 🟢  | Success |
| 🟠  | Warning |
| 🔴  | Failure |

## Notes

- logs: `/var/log/wazuh-indexer/wazuh-cluster.log`
- journalctl: `journalctl -xeu wazuh-indexer`
- service: `systemctl status wazuh-indexer`
- cluster state: `curl -X PUT "https://<WAZUH_INDEXER_IP>:9200/_cluster/health" -u <username>:<password>`
- For the installation, the [addition of the Wazuh repository](https://documentation.wazuh.com/current/installation-guide/wazuh-indexer/step-by-step.html#adding-the-wazuh-repository) can be skipped. Install the package directly (`yum localinstall <path-to-package>` or `dpkg -i <path-to-package>`).

**Comment by f-galland** [comment]
# `.deb` Packages validation:

### Dependency changes:

| Name | Status | Old Version | New Version |
|--------|---------|---------------|----------------|
|adduser|removed|||
|debconf|removed|||
|procps|removed|||
libasound2 |added ||>= 1.0.16|
libc6 |added ||>= 2.9|
libfreetype6 |added ||>= 2.3.5|
libx11-6 |added |||
libxext6 |added |||
libxi6 |added |||
libxrender1 |added |||
libxtst6 |added |||
zlib1g |added ||>= 1.2.2|

**Comment by f-galland** [comment]
# `.rpm` Packages validation:

### Shared libraries:
|Name |Status |Delta |Visual Diff|
|-----|-------|------|------|
|/usr/share/wazuh-indexer/plugins/opensearch-knn/lib/libgomp.so.1 |removed |||
|/usr/share/wazuh-indexer/plugins/opensearch-knn/lib/libopensearchknn_common.so |removed |||
|/usr/share/wazuh-indexer/plugins/opensearch-knn/lib/libopensearchknn_faiss.so |removed |||
|/usr/share/wazuh-indexer/plugins/opensearch-knn/lib/libopensearchknn_nmslib.so |removed |||

### Shell Programs:
|Name |Status |Delta |Visual|
|-----|-------|------|------|
|Diff|
|/usr/share/wazuh-indexer/plugins/opensearch-security/tools/install_demo_configuration.sh |added |||
|/usr/share/wazuh-indexer/bin/indexer-ism-init.sh |added |||
|/usr/share/wazuh-indexer/bin/indexer-init.sh |added |||
|/usr/share/wazuh-indexer/plugins/opensearch-security/tools/wazuh-passwords-tool.sh |removed |||
|/usr/share/wazuh-indexer/plugins/opensearch-security/tools/wazuh-certs-tool.sh |removed |||

### Configuration files:

|Name |Status |Delta |Visual Diff|
|-----|-------|------|------|
|/var/lib/wazuh-indexer/performance_analyzer_enabled.conf |added |||
|/var/lib/wazuh-indexer/rca_enabled.conf |added |||

### Symbolic Links:
|Name |Status |Delta |Visual Diff|
|-----|-------|------|------|
|/usr/share/wazuh-indexer/data |added |||
|/usr/share/wazuh-indexer/logs |added |||

### Policy Files:
|Name |Status |Delta |Visual Diff|
|-----|-------|------|------|
|/usr/share/wazuh-indexer/plugins/opensearch-geospatial/plugin-security.policy |added |||

### YAML Files:

|Name |Status |Delta |Visual Diff|
|-----|-------|------|------|
|/usr/share/wazuh-indexer/plugins/opensearch-security/tools/config.yml |removed |||

### Directories:
|Name |Status|
|-----|------|
|/var/run |added|
|/var/run/wazuh-indexer |added|
|/usr/share/wazuh-indexer/plugins/opensearch-knn/lib |removed|


### Archives:

|Name |Status |Delta |Visual|
|-----|-------|------|------|
|Diff|
|/usr/share/wazuh-indexer/lib/jakarta.annotation-api-1.3.5.jar |added |||
|/usr/share/wazuh-indexer/lib/jzlib-1.1.3.jar |added |||
|/usr/share/wazuh-indexer/lib/opensearch-common-2.11.1.jar |added |||
|/usr/share/wazuh-indexer/lib/opensearch-compress-2.11.1.jar |added |||
|/usr/share/wazuh-indexer/lib/opensearch-core-2.11.1.jar |added |||
|/usr/share/wazuh-indexer/lib/opensearch-telemetry-2.11.1.jar |added |||
|/usr/share/wazuh-indexer/lib/zstd-jni-1.5.5-5.jar |added |||
|/usr/share/wazuh-indexer/performance-analyzer-rca/lib/byte-buddy-1.9.0.jar |added |||
|/usr/share/wazuh-indexer/performance-analyzer-rca/lib/byte-buddy-agent-1.9.0.jar |added |||
|/usr/share/wazuh-indexer/performance-analyzer-rca/lib/jakarta.activation-2.0.0.jar |added |||
|/usr/share/wazuh-indexer/performance-analyzer-rca/lib/jakarta.annotation-api-1.3.5.jar |added |||
|/usr/share/wazuh-indexer/performance-analyzer-rca/lib/jakarta.xml.bind-api-3.0.0.jar |added |||
|/usr/share/wazuh-indexer/performance-analyzer-rca/lib/jooq-3.16.20.jar |added |||
|/usr/share/wazuh-indexer/performance-analyzer-rca/lib/mockito-core-2.23.0.jar |added |||
|/usr/share/wazuh-indexer/performance-analyzer-rca/lib/objenesis-2.6.jar |added |||
|/usr/share/wazuh-indexer/performance-analyzer-rca/lib/r2dbc-spi-0.9.0.RELEASE.jar |added |||
|/usr/share/wazuh-indexer/performance-analyzer-rca/lib/reactive-streams-1.0.3.jar |added |||
|/usr/share/wazuh-indexer/plugins/opensearch-alerting/kotlin-stdlib-jdk7-1.8.21.jar |added |||
|/usr/share/wazuh-indexer/plugins/opensearch-alerting/kotlin-stdlib-jdk8-1.8.21.jar |added |||
|/usr/share/wazuh-indexer/plugins/opensearch-anomaly-detection/randomcutforest-parkservices-3.8.0.jar |added |||
|/usr/share/wazuh-indexer/plugins/opensearch-cross-cluster-replication/kotlin-stdlib-jdk7-1.8.21.jar |added |||
|/usr/share/wazuh-indexer/plugins/opensearch-cross-cluster-replication/kotlin-stdlib-jdk8-1.8.21.jar |added |||
|/usr/share/wazuh-indexer/plugins/opensearch-geospatial/commons-csv-1.10.0.jar |added |||
|/usr/share/wazuh-indexer/plugins/opensearch-geospatial/ipaddress-5.4.0.jar |added |||
|/usr/share/wazuh-indexer/plugins/opensearch-geospatial/opensearch-geospatial-2.11.1.0.jar |added |||
|/usr/share/wazuh-indexer/plugins/opensearch-job-scheduler/google-java-format-1.17.0.jar |added |||
|/usr/share/wazuh-indexer/plugins/opensearch-ml/accessors-smart-2.4.9.jar |added |||
|/usr/share/wazuh-indexer/plugins/opensearch-ml/annotations-2.20.19.jar |added |||
|/usr/share/wazuh-indexer/plugins/opensearch-ml/apache-client-2.20.19.jar |added |||
|/usr/share/wazuh-indexer/plugins/opensearch-ml/asm-9.3.jar |added |||
|/usr/share/wazuh-indexer/plugins/opensearch-ml/auth-2.20.19.jar |added |||
|/usr/share/wazuh-indexer/plugins/opensearch-ml/aws-encryption-sdk-java-2.4.1.jar |added |||
|/usr/share/wazuh-indexer/plugins/opensearch-ml/bcprov-ext-jdk18on-1.75.jar |added |||
|/usr/share/wazuh-indexer/plugins/opensearch-ml/endpoints-spi-2.20.19.jar |added |||
|/usr/share/wazuh-indexer/plugins/opensearch-ml/eventstream-1.0.1.jar |added |||
|/usr/share/wazuh-indexer/plugins/opensearch-ml/http-client-spi-2.20.19.jar |added |||
|/usr/share/wazuh-indexer/plugins/opensearch-ml/httpcore5-5.2.1.jar |added |||
|/usr/share/wazuh-indexer/plugins/opensearch-ml/json-20231013.jar |added |||
|/usr/share/wazuh-indexer/plugins/opensearch-ml/json-path-2.8.0.jar |added |||
|/usr/share/wazuh-indexer/plugins/opensearch-ml/json-utils-2.20.19.jar |added |||
|/usr/share/wazuh-indexer/plugins/opensearch-ml/metrics-spi-2.20.19.jar |added |||
|/usr/share/wazuh-indexer/plugins/opensearch-ml/opensearch-ml-memory-2.11.1.0.jar |added |||
|/usr/share/wazuh-indexer/plugins/opensearch-ml/opensearch-ml-search-processors-2.11.1.0.jar |added |||
|/usr/share/wazuh-indexer/plugins/opensearch-ml/profiles-2.20.19.jar |added |||
|/usr/share/wazuh-indexer/plugins/opensearch-ml/reactive-streams-1.0.3.jar |added |||
|/usr/share/wazuh-indexer/plugins/opensearch-ml/regions-2.20.19.jar |added |||
|/usr/share/wazuh-indexer/plugins/opensearch-ml/sdk-core-2.20.19.jar |added |||
|/usr/share/wazuh-indexer/plugins/opensearch-ml/third-party-jackson-core-2.20.19.jar |added |||
|/usr/share/wazuh-indexer/plugins/opensearch-ml/utils-2.20.19.jar |added |||
|/usr/share/wazuh-indexer/plugins/opensearch-neural-search/commons-text-1.10.0.jar |added |||
|/usr/share/wazuh-indexer/plugins/opensearch-neural-search/gson-2.10.1.jar |added |||
|/usr/share/wazuh-indexer/plugins/opensearch-neural-search/json-20230227.jar |added |||
|/usr/share/wazuh-indexer/plugins/opensearch-neural-search/opensearch-neural-search-2.11.1.0.jar |added |||
|/usr/share/wazuh-indexer/plugins/opensearch-security-analytics/google-java-format-1.17.0.jar |added |||
|/usr/share/wazuh-indexer/plugins/opensearch-security-analytics/guava-32.0.1-jre.jar |added |||
|/usr/share/wazuh-indexer/plugins/opensearch-security/commons-io-2.13.0.jar |added |||
|/usr/share/wazuh-indexer/plugins/opensearch-security/commons-lang3-3.13.0.jar |added |||
|/usr/share/wazuh-indexer/plugins/opensearch-security/google-java-format-1.17.0.jar |added |||
|/usr/share/wazuh-indexer/plugins/opensearch-security/json-base-2.4.3.jar |added |||
|/usr/share/wazuh-indexer/plugins/opensearch-security/passay-1.6.4.jar |added |||
|/usr/share/wazuh-indexer/plugins/opensearch-security/scala-java8-compat_3-1.0.2.jar |added |||
|/usr/share/wazuh-indexer/plugins/opensearch-sql/aws-java-sdk-emr-1.12.545.jar |added |||
|/usr/share/wazuh-indexer/plugins/opensearch-sql/aws-java-sdk-emrserverless-1.12.545.jar |added |||
|/usr/share/wazuh-indexer/plugins/opensearch-sql/commons-beanutils-1.9.4.jar |added |||
|/usr/share/wazuh-indexer/plugins/opensearch-sql/commons-digester-2.1.jar |added |||
|/usr/share/wazuh-indexer/plugins/opensearch-sql/commons-validator-1.7.jar |added |||
|/usr/share/wazuh-indexer/plugins/opensearch-sql/ipaddress-5.4.0.jar |added |||
|/usr/share/wazuh-indexer/plugins/opensearch-sql/kotlin-stdlib-jdk7-1.9.0.jar |added |||
|/usr/share/wazuh-indexer/plugins/opensearch-sql/kotlin-stdlib-jdk8-1.8.0.jar |added |||
|/usr/share/wazuh-indexer/plugins/opensearch-sql/spark-2.11.1.0.jar |added |||
|/usr/share/wazuh-indexer/jdk/lib/jrt-fs.jar |changed |0.001% ||
|/usr/share/wazuh-indexer/plugins/opensearch-security/commons-collections-3.2.2.jar |moved |0% ||
|/usr/share/wazuh-indexer/plugins/opensearch-sql/commons-collections-3.2.2.jar |moved |0% ||
|/usr/share/wazuh-indexer/plugins/opensearch-security/json-smart-2.4.10.jar |moved |0% ||
|/usr/share/wazuh-indexer/plugins/opensearch-ml/json-smart-2.4.10.jar |moved |0% ||
|/usr/share/wazuh-indexer/lib/hppc-0.8.1.jar |removed |||
|/usr/share/wazuh-indexer/lib/opensearch-common-2.8.0.jar |removed |||
|/usr/share/wazuh-indexer/lib/opensearch-core-2.8.0.jar |removed |||
|/usr/share/wazuh-indexer/performance-analyzer-rca/lib/j2objc-annotations-1.3.jar |removed |||
|/usr/share/wazuh-indexer/performance-analyzer-rca/lib/javax.annotation-api-1.3.2.jar |removed |||
|/usr/share/wazuh-indexer/performance-analyzer-rca/lib/jooq-3.10.8.jar |removed |||
|/usr/share/wazuh-indexer/performance-analyzer-rca/lib/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar |removed |||
|/usr/share/wazuh-indexer/plugins/opensearch-alerting/kotlin-stdlib-jdk7-1.6.10.jar |removed |||
|/usr/share/wazuh-indexer/plugins/opensearch-alerting/kotlin-stdlib-jdk8-1.6.10.jar |removed |||
|/usr/share/wazuh-indexer/plugins/opensearch-anomaly-detection/randomcutforest-parkservices-3.0-rc3.jar |removed |||
|/usr/share/wazuh-indexer/plugins/opensearch-cross-cluster-replication/kotlin-stdlib-jdk7-1.6.0.jar |removed |||
|/usr/share/wazuh-indexer/plugins/opensearch-cross-cluster-replication/kotlin-stdlib-jdk8-1.6.0.jar |removed |||
|/usr/share/wazuh-indexer/plugins/opensearch-geospatial/opensearch-geospatial-2.8.0.0.jar |removed |||
|/usr/share/wazuh-indexer/plugins/opensearch-neural-search/opensearch-neural-search-2.8.0.0.jar |removed |||
|/usr/share/wazuh-indexer/plugins/opensearch-performance-analyzer/j2objc-annotations-1.3.jar |removed |||
|/usr/share/wazuh-indexer/plugins/opensearch-performance-analyzer/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar |removed |||
|/usr/share/wazuh-indexer/plugins/opensearch-security/commons-lang-2.4.jar |removed |||
|/usr/share/wazuh-indexer/plugins/opensearch-security/jakarta.annotation-api-1.3.5.jar |removed |||
|/usr/share/wazuh-indexer/plugins/opensearch-security/json-path-2.4.0.jar |removed |||
|/usr/share/wazuh-indexer/plugins/opensearch-security/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar |removed |||
|/usr/share/wazuh-indexer/plugins/opensearch-security/zstd-jni-1.5.2-1.jar |removed |||
|/usr/share/wazuh-indexer/plugins/opensearch-sql/kotlin-stdlib-jdk7-1.4.30.jar |removed |||

**Comment by f-galland** [comment]
# `.deb` package install:

Errors are thrown during installation on Ubuntu 22.04:
```bash
/usr/lib/tmpfiles.d/wazuh-indexer.conf:1: Failed to resolve user 'wazuh-indexer': No such process
Processing triggers for libc-bin (2.35-0ubuntu3.1) ...
Processing triggers for man-db (2.10.2-1) ...
needrestart is being skipped since dpkg has failed
```

Trying to start the service fails:
```bash
Jan 05 15:57:10 pkg-tests-ubuntu2204 systemd[1]: Starting wazuh-indexer...
Jan 05 15:57:10 pkg-tests-ubuntu2204 systemd[28927]: wazuh-indexer.service: Failed to determine user credentials: No such process
Jan 05 15:57:10 pkg-tests-ubuntu2204 systemd[28927]: wazuh-indexer.service: Failed at step USER spawning /usr/share/wazuh-indexer/bin/systemd-entrypoint: No such process
Jan 05 15:57:10 pkg-tests-ubuntu2204 systemd[1]: wazuh-indexer.service: Main process exited, code=exited, status=217/USER
Jan 05 15:57:10 pkg-tests-ubuntu2204 systemd[1]: wazuh-indexer.service: Failed with result 'exit-code'.
Jan 05 15:57:10 pkg-tests-ubuntu2204 systemd[1]: Failed to start wazuh-indexer.
```

**Comment by f-galland** [comment]
# `.rpm` package install:

Install throws errors on Alma Linux 8 as well:

```shell
[root@alma8 ~]# rpm -i wazuh-indexer-4.9.0-1.x86_64.rpm 
warning: %post(wazuh-indexer-4.9.0-1.x86_64) scriptlet failed, exit status 255
[/usr/lib/tmpfiles.d/wazuh-indexer.conf:1] Line references path below legacy directory /var/run/, updating /var/run/wazuh-indexer → /run/wazuh-indexer; please update the tmpfiles.d/ drop-in file accordingly.
```

**Comment by AlexRuiz7** [comment]
Issues than open from this testing:

- https://github.com/wazuh/wazuh-indexer/issues/101
- https://github.com/wazuh/wazuh-indexer/issues/102
- https://github.com/wazuh/wazuh-indexer/issues/103
- https://github.com/wazuh/wazuh-indexer/issues/104
- https://github.com/wazuh/wazuh-indexer/issues/105
- https://github.com/wazuh/wazuh-indexer/issues/106
- https://github.com/wazuh/wazuh-indexer/issues/107
- https://github.com/wazuh/wazuh-indexer/issues/108

Current testing iteration of wazuh-indexer@4.9.0 packages concluded with errors.
We'll work on these issues and open a new testing iteration.
